[project]
name = "cefet-scraper"
version = "0.1.0"
description = "Scraper para o portal de alunos do CEFET-RJ"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "requests>=2.32.4",
]
